apiVersion: v2
name: helm
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: rancher
    version: 2.6.6
    repository: https://releases.rancher.com/server-charts/stable
